### ISSUE TITLE
cannot install package from npm

### ISSUE THREAD

**Issue by k-makarov** [maxgherman/TypeIOC#6]
when i try to install typeioc package it throw this error:
![image](https://cloud.githubusercontent.com/assets/5754185/7114584/75d48166-e1e7-11e4-911a-734de3f0a8b6.png)

**Comment by maxgherman** [comment]
This is a known problem of working with C++ dependent packages under Windows. Depending on a version of Windows and VS you have installed, the solution could be as simple as 

npm install typeioc --msvs_version=<version>

where <version> could be 2012, 2013, or whatever VS is installed.

npm config could also be changed:

npm config set msvs_version <version>

For more permanent solution take a look at the answer for similar problem:
http://stackoverflow.com/questions/16469086/npm-cant-install-socket-io

Closing the issues since the latest build for Windows passes:
https://ci.appveyor.com/project/maxgherman/typeioc/build/22
